
-- WARNING NOT WORKING !!!
CREATE OR REPLACE TRIGGER TG_ARTISTE_NOT_BORN_BEFORE_PLAYED_ANY_ROLE 
AFTER INSERT OR UPDATE ON ARTISTE
FOR EACH ROW
BEGIN
    
    FOR DATE_SORTIE IN ( SELECT DATE_SORTIE FROM ROLE JOIN 
        FILM ON ROLE.FILM=FILM.ID_FILM WHERE ROLE.ACTEUR = 1)
        
    LOOP
            IF :NEW.DATE_NAISSANCE > DATE_SORTIE THEN
                RAISE_APPLICATION_ERROR(-20002, 'Acteur joue avant de naitre.');
            END IF;
    END LOOP;
END;

-- Insertion de données pour tester le trigger
INSERT INTO ARTISTE (ID_ARTISTE, NOM, PRENOM, DATE_NAISSANCE)
VALUES (3, 'Spielberg', 'Steven', to_date('18-12-1946', 'dd-mm-yyyy'));
INSERT INTO ARTISTE (ID_ARTISTE, NOM, PRENOM, DATE_NAISSANCE)
VALUES (2, 'Lucas', 'George', to_date('14-05-1944', 'dd-mm-yyyy'));

INSERT INTO FILM (ID_FILM, TITRE, DATE_SORTIE, REALISATEUR)
VALUES (1, 'American Graffiti', to_date('1973', 'yyyy'), 2);
INSERT INTO FILM (ID_FILM, TITRE, DATE_SORTIE, REALISATEUR)
VALUES (2, 'Le retour du Jedi', to_date('1973', 'yyyy'), 2);
INSERT INTO FILM (ID_FILM, TITRE, DATE_SORTIE, REALISATEUR)
VALUES (3, 'Ready Player One', to_date('2018', 'yyyy'), 3);

INSERT INTO ROLE (ACTEUR, FILM, ROLE)
VALUES (1, 1, 'Bob Falfa');
INSERT INTO ROLE (ACTEUR, FILM, ROLE)
VALUES (1, 2, 'Han Solo');