SELECT RIVER.NAME, COUNT(*) AS NB_LAKE FROM RIVERTHROUGH
JOIN RIVER ON RIVERTHROUGH.RIVER=RIVER.NAME
JOIN LAKE ON RIVERTHROUGH.LAKE=LAKE.NAME
WHERE RIVER.LENGTH > 3500 AND LAKE.DEPTH < 80
GROUP BY RIVER.NAME ORDER BY NB_LAKE DESC, RIVER.NAME;